apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-web
spec:
  type: NodePort
  selector:
    app: fastapi-web
  ports:
    - name: http
      port: 81
      targetPort: http
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
spec:
  selector:
    matchLabels:
      app: fastapi-web
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-web
    spec:
      containers:
      - name: pod-demo
